version: '3'
services:
  learner:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atari
    ports:
      - 8686:8686
    network_mode: "host"
    entrypoint: ["./docker/my_run.sh", "atari", "r2d2", "1", "4", "1", "192.93.8.119:8686", "disabled"]

  actor0:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atari
    ports:
      - 8687:8686
    network_mode: "host"
    depends_on:
      - learner
    entrypoint: ["./docker/my_run.sh", "atari", "r2d2", "1", "4", "0", "192.93.8.119:8686", "0"]


    #docker run --entrypoint ./docker/my_run.sh -ti -it -p 6006-6015:6006-6015 --network=host -e HOST_PERMS="$(id -u):$(id -g)" --name seed --rm seed_rl:atari atari r2d2 1 4 1 127.0.0.1:8686
    #docker run --entrypoint ./docker/my_run.sh -ti -it -p 6006-6015:6006-6015 --network=host -e HOST_PERMS="$(id -u):$(id -g)" --name seed --rm seed_rl:atari atari r2d2 1 4 0 127.0.0.1:8686 0
