version: '3'
services:
  learner:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atari
    ports:
      - 6006:6006
    networks:
      default:
        ipv4_address: 172.18.0.3
    entrypoint: ["./docker/my_run.sh", "atari", "r2d2", "4", "4", "1", "172.18.0.3:8686"]
  actor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atari
    ports:
      - 6007:6006
    networks:
      default:
        ipv4_address: 172.18.0.4
    depends_on:
      - learner
    entrypoint: ["./docker/my_run.sh", "atari", "r2d2", "4", "4", "0", "172.18.0.3:8686"]

